export const SET_KEYWORD = 'SET_KEYWORD';
export const GET_MOVIE_LIST = 'GET_MOVIE_LIST';
export const GET_MOVIE_LIST_LOADING = 'GET_MOVIE_LIST_LOADING';
export const GET_MOVIE_LIST_ERROR = 'GET_MOVIE_LIST_ERROR';
export const RESET_MOVIE_LIST = 'RESET_MOVIE_LIST';

export const ADD_FAVOURITE_MOVIE = 'ADD_FAVOURITE_MOVIE';
export const RESET_FAVOURITE_MOVIE = 'RESET_FAVOURITE_MOVIE';
export const REMOVE_FAVOURITE_MOVIE = 'REMOVE_FAVOURITE_MOVIE';
export const SET_FAVOURITE_MOVIES = 'SET_FAVOURITE_MOVIES';
